add_entity:
  description: "Add a new entity for trend calculation."
  fields:
    entity_id:
      description: "The entity to add."
      example: "sensor.temperature"
remove_entity:
  description: "Remove an existing entity from trend calculation."
  fields:
    entity_id:
      description: "The entity to remove."
      example: "sensor.temperature"
